### ISSUE TITLE
incorrect syntax in 3 structure factor files

### ISSUE THREAD

**Issue by wojdyr** [wwpdb-dictionaries/mmcif_pdbx#2]
It's not about dictionaries, but let me use this place to report three errors:

* divided/structure_factors/bq/r4bqtsf.ent.gz (see line 6)
* divided/structure_factors/yp/r2ypusf.ent.gz (unterminated text field)
* divided/structure_factors/zl/r3zllsf.ent.gz (unterminated 'string' in line 6)

**Comment by berrisfordjohn** [comment]
Hi
Thanks for letting us know about these issues. 
In the future please email deposit-help@mail.wwpdb.org for data issues like this and we will address them. 
These three structure factors have been fixed and will be available from the 15th November 2017. 

John

**Comment by wojdyr** [comment]
Thanks!
