### ISSUE TITLE
New proposed items for _struct_conf_type.id

### ISSUE THREAD

**Issue by drlemmus** [wwpdb-dictionaries/mmcif_pdbx#24]
To allow full DSSP compatibility we would like to have two additional secondary structure types defined in _struct_conf_type.id:
loop_
_item_enumeration.value
_item_enumeration.detail      
BEND	'region with high backbone curvature withou specific hydrogen bonding, a bend at residue i occurs when the angle between C_alpha(i)-C_alpha(i-2) and C_alpha(i+2)-C_alpha(i) is greater than 70 degrees (protein)'
OTHER    'secondary structure type that does not conform to an accepted category, random coil (protein)'

**Comment by wojdyr** [comment]
My comment is not directly about the request, but note that currently _struct_conf_type is used only for HELX_P (not counting TURN_P that is used in one or two entries). Beta-sheets are annotated using a different category.

**Comment by drlemmus** [comment]
That is exactly the reason why DSSP should be part of the annotation pipeline. The current annotation of secondary structure is very limited.

**Comment by epeisach** [comment]
I see that BEND was mentioned in the original Sanders paper - so logically should be included.  (I did not notice the 70 degrees part in first reading).

I guess OTHER is a catchall.  I have no issues with this.

**Comment by epeisach** [comment]
This has been updated in the dictionary now.

http://mmcif.wwpdb.org/dictionaries/mmcif_pdbx_v50.dic/Items/_struct_conf_type.id.html
