### ISSUE TITLE
inconsistency for pdbx_model_num

### ISSUE THREAD

**Issue by mhekkel** [wwpdb-dictionaries/mmcif_pdbx#27]
Header says:

5.297  2018-07-23
;
    Changes (ep):
    + Require _atom_site.pdbx_PDB_model_num non-zero positive integer
 
But then:
 
save__atom_site.pdbx_PDB_model_num
    _item_description.description
;   PDB model number.
;
...
    _item_range.maximum          .
    _item_range.minimum          0
     save_
 

Not that this is critical, but would be nice to know which is correct.

-maarten

**Comment by epeisach** [comment]
It is positive integer.

The issue is how to interpret item_range.

The above definition is 0 < x < inf

If you would like inclusive - then you would need
loop_
_item_range.maximum
_item_range.minimum
0 0 
.  0

This would be 0 <= x < inf

Does this clarify matters?

**Comment by mhekkel** [comment]
My bad, sorry.
