### ISSUE TITLE
_item_type.code of _entity.pdbx_number_of_molecules is float

### ISSUE THREAD

**Issue by arose** [wwpdb-dictionaries/mmcif_pdbx#3]
seems to me it should be int or can there be half-molecules?

**Comment by arose** [comment]
ping @epeisach, what do you think?

**Comment by epeisach** [comment]
I believe you are correct... This would change the pdml schema - but let me look into this.

**Comment by arose** [comment]
any news on this?

**Comment by epeisach** [comment]
I think this would work.  Let me check existing entries in archive to cleanup if present. (there should not be - but you never know)

**Comment by arose** [comment]
any update on this?

**Comment by epeisach** [comment]
Should be an int > 0.
Will update dictionary this weekend..

**Comment by arose** [comment]
Thank you

**Comment by epeisach** [comment]
This was changed to int - forgot to close issue
