### ISSUE TITLE
Item example for _entity_poly.pdbx_seq_one_letter_code

### ISSUE THREAD

**Issue by valasatava** [wwpdb-dictionaries/mmcif_pdbx#30]
Would it be possible to move this content:

A     for alanine or adenine
B     for ambiguous asparagine/aspartic-acid
R     for arginine
N     for asparagine
D     for aspartic-acid
C     for cysteine or cystine or cytosine
Q     for glutamine
E     for glutamic-acid
Z     for ambiguous glutamine/glutamic acid
G     for glycine or guanine
H     for histidine
I     for isoleucine
L     for leucine
K     for lysine
M     for methionine
F     for phenylalanine
P     for proline
S     for serine
T     for threonine or thymine
W     for tryptophan
Y     for tyrosine
V     for valine
U     for uracil
O     for water
X     for other
(MSE) for selenomethionine

from item example to description for _entity_poly.pdbx_seq_one_letter_code as it is done for _entity_poly.pdbx_seq_one_letter_code_can?

Thanks in advance!

**Comment by epeisach** [comment]
This is done now.  Please check.  I also provided a better example.

**Comment by valasatava** [comment]
Great! Thank you!
