### ISSUE TITLE
pdbx_formula_weight is used in current entries - documentation says otherwise

### ISSUE THREAD

**Issue by samirelanduk** [wwpdb-dictionaries/mmcif_pdbx#39]
The online [mmCIF dictionary documentation](https://mmcif.wwpdb.org/dictionaries/mmcif_pdbx_v50.dic/Items/_struct.pdbx_formula_weight.html) states that the `struct` category has a field `pdbx_formula_weight`, but states that is not used in currrent PDB entries.

In fact it seems that this data item is very widely used - [6FKT](https://files.rcsb.org/view/6FKT.cif) uses it to give just one of many examples.

**Comment by epeisach** [comment]
I will undertake a recalculation of usage.

**Comment by epeisach** [comment]
We have regenerated the counts.  However, you were explicitly asking about struct.pdbx_formula_weight in which there are no counts. I think you might be confusing presence in a model file with those containing data.  In CIF "?" is essentially an empty value - and we are not counting those. You mention 6FKT and you will notice that _struct.pdbx_formula_weight is "?".  Is this what you were referring to?

**Comment by samirelanduk** [comment]
Hi - thanks for looking into this. Yes that is what I was referring to. I think the language used is a little confusing on the page (I would argue that 6FKT is 'using' _struct.pdbx_formula_weight by having it present) but thank you for clarifying this.
