### ISSUE TITLE
make field usage percentage available for download

### ISSUE THREAD

**Issue by arose** [wwpdb-dictionaries/mmcif_pdbx#4]
The online documentation (at http://mmcif.wwpdb.org/) contains a usage percentage (in current PDB entries) for each field, e.g. http://mmcif.wwpdb.org/dictionaries/mmcif_pdbx_v50.dic/Categories/atom_site.html states "Used in current PDB entries: Yes, in about 100.0 % of entries".

I was wondering if those field usage percentages can be made available for download as a single file for the whole dictionary?

**Comment by wojdyr** [comment]
See: https://project-gemmi.github.io/pdb-stats/tags.html
(the raw data is stored in TSV files in the github repository linked at the bottom of that page)

**Comment by arose** [comment]
thanks @wojdyr!
