### ISSUE TITLE
hydrog in _struct_conn.conn_type_id enumeration

### ISSUE THREAD

**Issue by wojdyr** [wwpdb-dictionaries/mmcif_pdbx#5]
Is it intentional that mmcif_pdbx-base.dic doesn't allow `hydrog` as a value for `_struct_conn.conn_type_id`? I'm asking because it's the most popular `conn_type_id` in wwPDB entries. I was just looking at statistics:
```
4035115 hydrog
1394732 metalc
 501851 covale
 184231 disulf
```

and the dictionary has only three enumeration values:
```
save__struct_conn.conn_type_id
    _item_description.description
;              This data item is a pointer to _struct_conn_type.id in the
               STRUCT_CONN_TYPE category.
;
    _item.name                  '_struct_conn.conn_type_id'
    _item.mandatory_code          yes
    loop_
    _pdbx_item_enumeration.name
    _pdbx_item_enumeration.value
    _pdbx_item_enumeration.detail
      "_struct_conn.conn_type_id"  covale  .  
      "_struct_conn.conn_type_id"  disulf  .  
      "_struct_conn.conn_type_id"  metalc  .  
   #
     save_
```

**Comment by epeisach** [comment]
I am sorry for not responding previously.  There are two types of enumeration in the dictionary.  Those identified by item_enumeration and the others by pdbx_item_enumeration.

Files produced by the wwPDB use are constrained with item_enumeration.  All entries in the archive are required to conform to this. So it is possible that one believes an enumeration should be present - unless the archive conforms to it - we cannnot implement it.

pdbx_item_enumeration is an enumeration used by our deposition system.  This enumeration might be a subset of the enumeration available for the archive.

pdbx_database_related.content_type shows this scenario.

http://mmcif.wwpdb.org/dictionaries/mmcif_pdbx_v50.dic/Items/_pdbx_database_related.content_type.html

I will see if our archive would support an enumeration for struct_conn.conn_type_id and add it possible.

**Comment by epeisach** [comment]
Based on analysis of our archive, we use only four values for the whole archive 
hydrog
covale
metalc
disulf

I will update our dictionary this weekend

**Comment by arose** [comment]
Thanks!

**Comment by epeisach** [comment]
Correction - this was updated last February and is already out there.
