### ISSUE TITLE
aggregate atom identifier is not a unique identifier

### ISSUE THREAD

**Issue by wojdyr** [wwpdb-dictionaries/mmcif_pdbx#6]
The dictionary says in one place:

>  In a macromolecular CIF, the atom identifier is the aggregate of _atom_site.label_alt_id, _atom_site.label_asym_id, _atom_site.label_atom_id, _atom_site.label_comp_id and _atom_site.label_seq_id.

I think it would be good to add that in general this aggregate identifier does not uniquely identify an atom site (because it's not unique for waters), so it is of limited use.

**Comment by epeisach** [comment]
I believe you are correct.  I will look to correct the documentation.

**Comment by epeisach** [comment]
I am updating the dictionary with the following paragraph (it is the description for atom_site)

In general, this aggregate identifier does not uniquely
identify an atom site as for non-polymers _atom_site.label_seq_id
is '.'
