### ISSUE TITLE
Issue with _pdbx_domain_range in mmCIF

### ISSUE THREAD

**Issue by gtauriello** [wwpdb-dictionaries/mmcif_pdbx#60]
I am working on a model set for ModelArchive (using the mmCIF extension ModelCIF) and would like to use mmCIF's _pdbx_domain, _pdbx_feature_domain, and _pdbx_domain_range categories to store computationally annotated domains.

The problem now is that I struggle to create valid files because of _pdbx_domain_range.beg_label_alt_id and .end_label_alt_id. Those are part of the unique key and point to _atom_site.label_alt_id. In my files (and in so many other instances), _atom_site.label_alt_id is '.'. Unfortunately, this is not an allowed value for unique keys and hence I cannot create valid files (unless I artificially define a value for label_alt_id for all atoms)...

I discussed the issue with Brinda who told me that the solution in other categories (e.g. _pdbx_validate_close_contact) is to simply not have label_alt_id as part of the key.
Would that also be possible for _pdbx_domain_range to allow its use in cases with _atom_site.label_alt_id = '.'?

**Comment by brindakv** [comment]
@gtauriello This should now be addressed in https://github.com/ihmwg/ModelCIF/pull/25.
